export type ElementId = string;

export interface ElementDef {
  id: ElementId;
  name: string;
  emoji: string;
}

export const BASE_ELEMENT_IDS: ElementId[] = ['water', 'fire', 'wind', 'earth'];

export const ELEMENTS: Record<ElementId, ElementDef> = {
  water: { id: 'water', name: 'Su', emoji: '💧' },
  fire: { id: 'fire', name: 'Ateş', emoji: '🔥' },
  wind: { id: 'wind', name: 'Rüzgar', emoji: '🌬️' },
  earth: { id: 'earth', name: 'Toprak', emoji: '🌍' },

  steam: { id: 'steam', name: 'Buhar', emoji: '💨' },
  mud: { id: 'mud', name: 'Çamur', emoji: '🟫' },
  wave: { id: 'wave', name: 'Dalga', emoji: '🌊' },
  lava: { id: 'lava', name: 'Lav', emoji: '🌋' },
  smoke: { id: 'smoke', name: 'Duman', emoji: '🌫️' },
  dust: { id: 'dust', name: 'Toz', emoji: '🏜️' },
  lake: { id: 'lake', name: 'Göl', emoji: '🏞️' },
  sun: { id: 'sun', name: 'Güneş', emoji: '☀️' },
  tornado: { id: 'tornado', name: 'Kasırga', emoji: '🌪️' },
  mountain: { id: 'mountain', name: 'Dağ', emoji: '⛰️' },

  cloud: { id: 'cloud', name: 'Bulut', emoji: '☁️' },
  rain: { id: 'rain', name: 'Yağmur', emoji: '🌧️' },
  brick: { id: 'brick', name: 'Tuğla', emoji: '🧱' },
  clay: { id: 'clay', name: 'Kil', emoji: '🏺' },
  stone: { id: 'stone', name: 'Taş', emoji: '🪨' },
  ash: { id: 'ash', name: 'Kül', emoji: '🩶' },
  glass: { id: 'glass', name: 'Cam', emoji: '🪟' },
  rainbow: { id: 'rainbow', name: 'Gökkuşağı', emoji: '🌈' },
  desert: { id: 'desert', name: 'Çöl', emoji: '🐫' },
  hurricane: { id: 'hurricane', name: 'Kasırga Fırtınası', emoji: '🌀' },
  island: { id: 'island', name: 'Ada', emoji: '🏝️' },
  mist: { id: 'mist', name: 'Sis', emoji: '🌁' },
  volcano: { id: 'volcano', name: 'Yanardağ', emoji: '🗻' },
  plant: { id: 'plant', name: 'Bitki', emoji: '🌱' },

  tree: { id: 'tree', name: 'Ağaç', emoji: '🌳' },
  flower: { id: 'flower', name: 'Çiçek', emoji: '🌸' },
  life: { id: 'life', name: 'Yaşam', emoji: '🧬' },
  fish: { id: 'fish', name: 'Balık', emoji: '🐟' },
  animal: { id: 'animal', name: 'Hayvan', emoji: '🐾' },
  metal: { id: 'metal', name: 'Metal', emoji: '⚙️' },
  dragon: { id: 'dragon', name: 'Ejderha', emoji: '🐉' },
  phoenix: { id: 'phoenix', name: 'Anka Kuşu', emoji: '🪶' },
  human: { id: 'human', name: 'İnsan', emoji: '🧍' },
  boat: { id: 'boat', name: 'Kayık', emoji: '⛵' },
  farmland: { id: 'farmland', name: 'Tarla', emoji: '🌾' },

  tool: { id: 'tool', name: 'Alet', emoji: '🔨' },
  sword: { id: 'sword', name: 'Kılıç', emoji: '⚔️' },
  house: { id: 'house', name: 'Ev', emoji: '🏠' },
  ship: { id: 'ship', name: 'Gemi', emoji: '🚢' },
  village: { id: 'village', name: 'Köy', emoji: '🏘️' },
  city: { id: 'city', name: 'Şehir', emoji: '🏙️' },
  machine: { id: 'machine', name: 'Makine', emoji: '🤖' },
  robot: { id: 'robot', name: 'Robot', emoji: '🦾' },
  farmer: { id: 'farmer', name: 'Çiftçi', emoji: '👨‍🌾' },
  sailor: { id: 'sailor', name: 'Denizci', emoji: '⛴️' },

  // Hava durumu ve coğrafya
  storm: { id: 'storm', name: 'Fırtına', emoji: '⛈️' },
  lightning: { id: 'lightning', name: 'Şimşek', emoji: '⚡' },
  thunder: { id: 'thunder', name: 'Gök Gürültüsü', emoji: '🔊' },
  snow: { id: 'snow', name: 'Kar', emoji: '❄️' },
  ice: { id: 'ice', name: 'Buz', emoji: '🧊' },
  blizzard: { id: 'blizzard', name: 'Tipi', emoji: '🌨️' },
  glacier: { id: 'glacier', name: 'Buzul', emoji: '🏔️' },
  sand: { id: 'sand', name: 'Kum', emoji: '🟨' },
  beach: { id: 'beach', name: 'Plaj', emoji: '🏖️' },
  swamp: { id: 'swamp', name: 'Bataklık', emoji: '🐊' },
  oasis: { id: 'oasis', name: 'Vaha', emoji: '🌴' },
  river: { id: 'river', name: 'Nehir', emoji: '🏞️' },

  // Malzemeler
  coal: { id: 'coal', name: 'Kömür', emoji: '⚫' },
  gem: { id: 'gem', name: 'Değerli Taş', emoji: '💠' },
  diamond: { id: 'diamond', name: 'Elmas', emoji: '💎' },
  gold: { id: 'gold', name: 'Altın', emoji: '🪙' },
  jewelry: { id: 'jewelry', name: 'Mücevher', emoji: '💍' },
  rust: { id: 'rust', name: 'Pas', emoji: '🟠' },
  electricity: { id: 'electricity', name: 'Elektrik', emoji: '🔌' },
  oil: { id: 'oil', name: 'Petrol', emoji: '🛢️' },
  plastic: { id: 'plastic', name: 'Plastik', emoji: '🧴' },
  concrete: { id: 'concrete', name: 'Beton', emoji: '⬜' },
  wire: { id: 'wire', name: 'Tel', emoji: '➰' },
  magnet: { id: 'magnet', name: 'Mıknatıs', emoji: '🧲' },
  steel: { id: 'steel', name: 'Çelik', emoji: '🔩' },
  bronze: { id: 'bronze', name: 'Bronz', emoji: '🥉' },

  // Canlılar
  bird: { id: 'bird', name: 'Kuş', emoji: '🐦' },
  egg: { id: 'egg', name: 'Yumurta', emoji: '🥚' },
  insect: { id: 'insect', name: 'Böcek', emoji: '🐛' },
  bee: { id: 'bee', name: 'Arı', emoji: '🐝' },
  honey: { id: 'honey', name: 'Bal', emoji: '🍯' },
  spider: { id: 'spider', name: 'Örümcek', emoji: '🕷️' },
  ocean: { id: 'ocean', name: 'Okyanus', emoji: '🌊' },
  whale: { id: 'whale', name: 'Balina', emoji: '🐋' },
  shark: { id: 'shark', name: 'Köpekbalığı', emoji: '🦈' },
  coral: { id: 'coral', name: 'Mercan', emoji: '🪸' },
  snake: { id: 'snake', name: 'Yılan', emoji: '🐍' },
  forest: { id: 'forest', name: 'Orman', emoji: '🌲' },
  wolf: { id: 'wolf', name: 'Kurt', emoji: '🐺' },
  bear: { id: 'bear', name: 'Ayı', emoji: '🐻' },
  monkey: { id: 'monkey', name: 'Maymun', emoji: '🐒' },
  cow: { id: 'cow', name: 'İnek', emoji: '🐄' },
  milk: { id: 'milk', name: 'Süt', emoji: '🥛' },
  cheese: { id: 'cheese', name: 'Peynir', emoji: '🧀' },
  sheep: { id: 'sheep', name: 'Koyun', emoji: '🐑' },
  wool: { id: 'wool', name: 'Yün', emoji: '🧶' },
  chicken: { id: 'chicken', name: 'Tavuk', emoji: '🐔' },
  pig: { id: 'pig', name: 'Domuz', emoji: '🐷' },
  dinosaur: { id: 'dinosaur', name: 'Dinozor', emoji: '🦕' },
  bacteria: { id: 'bacteria', name: 'Bakteri', emoji: '🦠' },
  virus: { id: 'virus', name: 'Virüs', emoji: '🧫' },

  // Uygarlık
  king: { id: 'king', name: 'Kral', emoji: '👑' },
  queen: { id: 'queen', name: 'Kraliçe', emoji: '👸' },
  knight: { id: 'knight', name: 'Şövalye', emoji: '🛡️' },
  castle: { id: 'castle', name: 'Kale', emoji: '🏰' },
  kingdom: { id: 'kingdom', name: 'Krallık', emoji: '🏴' },
  army: { id: 'army', name: 'Ordu', emoji: '🎖️' },
  war: { id: 'war', name: 'Savaş', emoji: '💥' },
  peace: { id: 'peace', name: 'Barış', emoji: '☮️' },
  gun: { id: 'gun', name: 'Silah', emoji: '🔫' },
  bomb: { id: 'bomb', name: 'Bomba', emoji: '💣' },
  nuclear: { id: 'nuclear', name: 'Nükleer', emoji: '☢️' },
  money: { id: 'money', name: 'Para', emoji: '💵' },
  market: { id: 'market', name: 'Pazar', emoji: '🏪' },
  bank: { id: 'bank', name: 'Banka', emoji: '🏦' },
  factory: { id: 'factory', name: 'Fabrika', emoji: '🏭' },
  tower: { id: 'tower', name: 'Kule', emoji: '🗼' },
  bridge: { id: 'bridge', name: 'Köprü', emoji: '🌉' },
  temple: { id: 'temple', name: 'Tapınak', emoji: '⛩️' },
  church: { id: 'church', name: 'Kilise', emoji: '⛪' },

  // Teknoloji
  computer: { id: 'computer', name: 'Bilgisayar', emoji: '💻' },
  internet: { id: 'internet', name: 'İnternet', emoji: '🌐' },
  phone: { id: 'phone', name: 'Telefon', emoji: '📱' },
  television: { id: 'television', name: 'Televizyon', emoji: '📺' },
  camera: { id: 'camera', name: 'Kamera', emoji: '📷' },
  rocket: { id: 'rocket', name: 'Roket', emoji: '🚀' },
  satellite: { id: 'satellite', name: 'Uydu', emoji: '🛰️' },
  astronaut: { id: 'astronaut', name: 'Astronot', emoji: '👨‍🚀' },
  alien: { id: 'alien', name: 'Uzaylı', emoji: '👽' },
  ufo: { id: 'ufo', name: 'UFO', emoji: '🛸' },
  airplane: { id: 'airplane', name: 'Uçak', emoji: '✈️' },
  wheel: { id: 'wheel', name: 'Tekerlek', emoji: '🛞' },
  car: { id: 'car', name: 'Araba', emoji: '🚗' },
  train: { id: 'train', name: 'Tren', emoji: '🚂' },
  ai: { id: 'ai', name: 'Yapay Zeka', emoji: '🧠' },

  // Uzay
  star: { id: 'star', name: 'Yıldız', emoji: '⭐' },
  moon: { id: 'moon', name: 'Ay', emoji: '🌙' },
  comet: { id: 'comet', name: 'Kuyruklu Yıldız', emoji: '☄️' },
  meteor: { id: 'meteor', name: 'Meteor', emoji: '🌠' },
  planet: { id: 'planet', name: 'Gezegen', emoji: '🪐' },
  galaxy: { id: 'galaxy', name: 'Galaksi', emoji: '🌌' },
  universe: { id: 'universe', name: 'Evren', emoji: '♾️' },
  blackhole: { id: 'blackhole', name: 'Kara Delik', emoji: '🕳️' },

  // Mitoloji ve fantazya
  ghost: { id: 'ghost', name: 'Hayalet', emoji: '👻' },
  god: { id: 'god', name: 'Tanrı', emoji: '🌟' },
  angel: { id: 'angel', name: 'Melek', emoji: '👼' },
  devil: { id: 'devil', name: 'Şeytan', emoji: '😈' },
  demon: { id: 'demon', name: 'İblis', emoji: '👹' },
  zombie: { id: 'zombie', name: 'Zombi', emoji: '🧟' },
  night: { id: 'night', name: 'Gece', emoji: '🌃' },
  bat: { id: 'bat', name: 'Yarasa', emoji: '🦇' },
  vampire: { id: 'vampire', name: 'Vampir', emoji: '🧛' },
  werewolf: { id: 'werewolf', name: 'Kurt Adam', emoji: '🌕' },
  magic: { id: 'magic', name: 'Büyü', emoji: '🪄' },
  witch: { id: 'witch', name: 'Cadı', emoji: '🧙‍♀️' },
  wizard: { id: 'wizard', name: 'Büyücü', emoji: '🧙' },
  horse: { id: 'horse', name: 'At', emoji: '🐴' },
  unicorn: { id: 'unicorn', name: 'Tek Boynuzlu At', emoji: '🦄' },
  mermaid: { id: 'mermaid', name: 'Deniz Kızı', emoji: '🧜‍♀️' },
  monster: { id: 'monster', name: 'Canavar', emoji: '👾' },
  kraken: { id: 'kraken', name: 'Kraken', emoji: '🐙' },

  // Yiyecek
  wheat: { id: 'wheat', name: 'Buğday', emoji: '🌾' },
  flour: { id: 'flour', name: 'Un', emoji: '🥣' },
  bread: { id: 'bread', name: 'Ekmek', emoji: '🍞' },
  rice: { id: 'rice', name: 'Pirinç', emoji: '🍚' },
  sugar: { id: 'sugar', name: 'Şeker', emoji: '🍬' },
  cake: { id: 'cake', name: 'Pasta', emoji: '🍰' },
  wine: { id: 'wine', name: 'Şarap', emoji: '🍷' },
  beer: { id: 'beer', name: 'Bira', emoji: '🍺' },
  coffee: { id: 'coffee', name: 'Kahve', emoji: '☕' },
  leaf: { id: 'leaf', name: 'Yaprak', emoji: '🍃' },
  tea: { id: 'tea', name: 'Çay', emoji: '🍵' },
  chocolate: { id: 'chocolate', name: 'Çikolata', emoji: '🍫' },
  icecream: { id: 'icecream', name: 'Dondurma', emoji: '🍦' },
  pizza: { id: 'pizza', name: 'Pizza', emoji: '🍕' },
  salt: { id: 'salt', name: 'Tuz', emoji: '🧂' },

  // Soyut kavramlar
  time: { id: 'time', name: 'Zaman', emoji: '⏳' },
  love: { id: 'love', name: 'Aşk', emoji: '❤️' },
  music: { id: 'music', name: 'Müzik', emoji: '🎵' },
  art: { id: 'art', name: 'Sanat', emoji: '🎨' },
  dance: { id: 'dance', name: 'Dans', emoji: '💃' },
  dream: { id: 'dream', name: 'Rüya', emoji: '💭' },
  nightmare: { id: 'nightmare', name: 'Kabus', emoji: '😱' },
  soul: { id: 'soul', name: 'Ruh', emoji: '✨' },
};

function key(a: ElementId, b: ElementId): string {
  return [a, b].sort().join('+');
}

const RAW_RECIPES: [ElementId, ElementId, ElementId][] = [
  ['water', 'fire', 'steam'],
  ['water', 'earth', 'mud'],
  ['water', 'wind', 'wave'],
  ['fire', 'earth', 'lava'],
  ['fire', 'wind', 'smoke'],
  ['earth', 'wind', 'dust'],
  ['water', 'water', 'lake'],
  ['fire', 'fire', 'sun'],
  ['wind', 'wind', 'tornado'],
  ['earth', 'earth', 'mountain'],

  ['steam', 'wind', 'cloud'],
  ['cloud', 'water', 'rain'],
  ['mud', 'fire', 'brick'],
  ['mud', 'wind', 'clay'],
  ['lava', 'water', 'stone'],
  ['lava', 'wind', 'ash'],
  ['dust', 'fire', 'glass'],
  ['sun', 'rain', 'rainbow'],
  ['sun', 'earth', 'desert'],
  ['tornado', 'water', 'hurricane'],
  ['lake', 'earth', 'island'],
  ['lake', 'wind', 'mist'],
  ['mountain', 'fire', 'volcano'],
  ['rain', 'earth', 'plant'],

  ['plant', 'water', 'tree'],
  ['plant', 'sun', 'flower'],
  ['plant', 'earth', 'life'],
  ['life', 'water', 'fish'],
  ['life', 'earth', 'animal'],
  ['stone', 'fire', 'metal'],
  ['animal', 'fire', 'dragon'],
  ['life', 'fire', 'phoenix'],
  ['life', 'life', 'human'],
  ['human', 'water', 'boat'],
  ['plant', 'rain', 'farmland'],

  ['metal', 'human', 'tool'],
  ['tool', 'fire', 'sword'],
  ['human', 'tree', 'house'],
  ['boat', 'wind', 'ship'],
  ['house', 'house', 'village'],
  ['village', 'village', 'city'],
  ['city', 'metal', 'machine'],
  ['machine', 'city', 'robot'],
  ['human', 'farmland', 'farmer'],
  ['ship', 'human', 'sailor'],

  // Hava durumu ve coğrafya
  ['cloud', 'cloud', 'storm'],
  ['storm', 'fire', 'lightning'],
  ['lightning', 'wind', 'thunder'],
  ['cloud', 'wind', 'snow'],
  ['snow', 'water', 'ice'],
  ['snow', 'wind', 'blizzard'],
  ['ice', 'mountain', 'glacier'],
  ['desert', 'wind', 'sand'],
  ['sand', 'wave', 'beach'],
  ['rain', 'mud', 'swamp'],
  ['desert', 'water', 'oasis'],
  ['mountain', 'rain', 'river'],

  // Malzemeler
  ['tree', 'fire', 'coal'],
  ['lava', 'rainbow', 'gem'],
  ['coal', 'stone', 'diamond'],
  ['sand', 'fire', 'gold'],
  ['diamond', 'metal', 'jewelry'],
  ['metal', 'water', 'rust'],
  ['lightning', 'metal', 'electricity'],
  ['sand', 'lava', 'oil'],
  ['oil', 'fire', 'plastic'],
  ['stone', 'sand', 'concrete'],
  ['metal', 'electricity', 'wire'],
  ['metal', 'metal', 'magnet'],
  ['metal', 'coal', 'steel'],
  ['metal', 'stone', 'bronze'],

  // Canlılar
  ['animal', 'wind', 'bird'],
  ['bird', 'earth', 'egg'],
  ['plant', 'animal', 'insect'],
  ['insect', 'flower', 'bee'],
  ['bee', 'flower', 'honey'],
  ['insect', 'insect', 'spider'],
  ['wave', 'wave', 'ocean'],
  ['ocean', 'fish', 'whale'],
  ['ocean', 'dragon', 'shark'],
  ['ocean', 'plant', 'coral'],
  ['animal', 'desert', 'snake'],
  ['tree', 'tree', 'forest'],
  ['forest', 'animal', 'wolf'],
  ['forest', 'fish', 'bear'],
  ['tree', 'animal', 'monkey'],
  ['farmland', 'animal', 'cow'],
  ['cow', 'water', 'milk'],
  ['milk', 'sun', 'cheese'],
  ['farmland', 'wind', 'sheep'],
  ['sheep', 'tool', 'wool'],
  ['egg', 'farmland', 'chicken'],
  ['farmland', 'mud', 'pig'],
  ['egg', 'volcano', 'dinosaur'],
  ['swamp', 'life', 'bacteria'],
  ['bacteria', 'animal', 'virus'],

  // Uygarlık
  ['human', 'gold', 'king'],
  ['king', 'jewelry', 'queen'],
  ['human', 'sword', 'knight'],
  ['king', 'stone', 'castle'],
  ['castle', 'village', 'kingdom'],
  ['knight', 'knight', 'army'],
  ['army', 'army', 'war'],
  ['war', 'flower', 'peace'],
  ['metal', 'fire', 'gun'],
  ['gun', 'fire', 'bomb'],
  ['bomb', 'electricity', 'nuclear'],
  ['gold', 'city', 'money'],
  ['money', 'village', 'market'],
  ['money', 'city', 'bank'],
  ['machine', 'coal', 'factory'],
  ['brick', 'brick', 'tower'],
  ['river', 'stone', 'bridge'],
  ['stone', 'life', 'temple'],
  ['temple', 'village', 'church'],

  // Teknoloji
  ['machine', 'electricity', 'computer'],
  ['computer', 'wire', 'internet'],
  ['internet', 'human', 'phone'],
  ['electricity', 'glass', 'television'],
  ['glass', 'machine', 'camera'],
  ['machine', 'fire', 'rocket'],
  ['rocket', 'wire', 'satellite'],
  ['human', 'satellite', 'astronaut'],
  ['satellite', 'life', 'alien'],
  ['alien', 'machine', 'ufo'],
  ['machine', 'wind', 'airplane'],
  ['stone', 'tool', 'wheel'],
  ['machine', 'wheel', 'car'],
  ['car', 'car', 'train'],
  ['computer', 'life', 'ai'],

  // Uzay
  ['sun', 'sun', 'star'],
  ['star', 'earth', 'moon'],
  ['star', 'ice', 'comet'],
  ['comet', 'fire', 'meteor'],
  ['moon', 'star', 'planet'],
  ['planet', 'planet', 'galaxy'],
  ['galaxy', 'galaxy', 'universe'],
  ['universe', 'volcano', 'blackhole'],

  // Mitoloji ve fantazya
  ['human', 'wind', 'ghost'],
  ['human', 'sun', 'god'],
  ['god', 'bird', 'angel'],
  ['god', 'fire', 'devil'],
  ['devil', 'ghost', 'demon'],
  ['human', 'virus', 'zombie'],
  ['sun', 'moon', 'night'],
  ['bird', 'night', 'bat'],
  ['human', 'bat', 'vampire'],
  ['human', 'wolf', 'werewolf'],
  ['life', 'rainbow', 'magic'],
  ['human', 'magic', 'witch'],
  ['witch', 'tool', 'wizard'],
  ['animal', 'village', 'horse'],
  ['horse', 'magic', 'unicorn'],
  ['fish', 'human', 'mermaid'],
  ['demon', 'animal', 'monster'],
  ['ocean', 'monster', 'kraken'],

  // Yiyecek
  ['farmland', 'farmland', 'wheat'],
  ['wheat', 'stone', 'flour'],
  ['flour', 'fire', 'bread'],
  ['farmland', 'rain', 'rice'],
  ['farmland', 'sun', 'sugar'],
  ['bread', 'sugar', 'cake'],
  ['water', 'sugar', 'wine'],
  ['wheat', 'water', 'beer'],
  ['farmland', 'fire', 'coffee'],
  ['tree', 'wind', 'leaf'],
  ['leaf', 'water', 'tea'],
  ['sugar', 'milk', 'chocolate'],
  ['milk', 'ice', 'icecream'],
  ['bread', 'cheese', 'pizza'],
  ['ocean', 'sun', 'salt'],

  // Soyut kavramlar
  ['sun', 'sand', 'time'],
  ['human', 'human', 'love'],
  ['human', 'bird', 'music'],
  ['human', 'flower', 'art'],
  ['music', 'human', 'dance'],
  ['human', 'night', 'dream'],
  ['dream', 'demon', 'nightmare'],
  ['human', 'ghost', 'soul'],
];

export const RECIPES: Record<string, ElementId> = {};
for (const [a, b, result] of RAW_RECIPES) {
  RECIPES[key(a, b)] = result;
}

export function combine(a: ElementId, b: ElementId): ElementId | null {
  return RECIPES[key(a, b)] ?? null;
}
